// Code generated by MockGen. DO NOT EDIT.
// Source: pool.go
//
// Generated by this command:
//
//	mockgen -source=pool.go -destination=mock_pool.go -package=ipfs -typed
//

// Package ipfs is a generated GoMock package.
package ipfs

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPool is a mock of IPool interface.
type MockIPool struct {
	ctrl     *gomock.Controller
	recorder *MockIPoolMockRecorder
	isgomock struct{}
}

// MockIPoolMockRecorder is the mock recorder for MockIPool.
type MockIPoolMockRecorder struct {
	mock *MockIPool
}

// NewMockIPool creates a new mock instance.
func NewMockIPool(ctrl *gomock.Controller) *MockIPool {
	mock := &MockIPool{ctrl: ctrl}
	mock.recorder = &MockIPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPool) EXPECT() *MockIPoolMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIPool) Get(ctx context.Context, link string) (Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, link)
	ret0, _ := ret[0].(Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIPoolMockRecorder) Get(ctx, link any) *MockIPoolGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIPool)(nil).Get), ctx, link)
	return &MockIPoolGetCall{Call: call}
}

// MockIPoolGetCall wrap *gomock.Call
type MockIPoolGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPoolGetCall) Return(arg0 Data, arg1 error) *MockIPoolGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPoolGetCall) Do(f func(context.Context, string) (Data, error)) *MockIPoolGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPoolGetCall) DoAndReturn(f func(context.Context, string) (Data, error)) *MockIPoolGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetFromNode mocks base method.
func (m *MockIPool) GetFromNode(ctx context.Context, link, node string) (Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromNode", ctx, link, node)
	ret0, _ := ret[0].(Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromNode indicates an expected call of GetFromNode.
func (mr *MockIPoolMockRecorder) GetFromNode(ctx, link, node any) *MockIPoolGetFromNodeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromNode", reflect.TypeOf((*MockIPool)(nil).GetFromNode), ctx, link, node)
	return &MockIPoolGetFromNodeCall{Call: call}
}

// MockIPoolGetFromNodeCall wrap *gomock.Call
type MockIPoolGetFromNodeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPoolGetFromNodeCall) Return(arg0 Data, arg1 error) *MockIPoolGetFromNodeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPoolGetFromNodeCall) Do(f func(context.Context, string, string) (Data, error)) *MockIPoolGetFromNodeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPoolGetFromNodeCall) DoAndReturn(f func(context.Context, string, string) (Data, error)) *MockIPoolGetFromNodeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetFromRandomGateway mocks base method.
func (m *MockIPool) GetFromRandomGateway(ctx context.Context, link string) (Data, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromRandomGateway", ctx, link)
	ret0, _ := ret[0].(Data)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromRandomGateway indicates an expected call of GetFromRandomGateway.
func (mr *MockIPoolMockRecorder) GetFromRandomGateway(ctx, link any) *MockIPoolGetFromRandomGatewayCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromRandomGateway", reflect.TypeOf((*MockIPool)(nil).GetFromRandomGateway), ctx, link)
	return &MockIPoolGetFromRandomGatewayCall{Call: call}
}

// MockIPoolGetFromRandomGatewayCall wrap *gomock.Call
type MockIPoolGetFromRandomGatewayCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIPoolGetFromRandomGatewayCall) Return(arg0 Data, arg1 error) *MockIPoolGetFromRandomGatewayCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIPoolGetFromRandomGatewayCall) Do(f func(context.Context, string) (Data, error)) *MockIPoolGetFromRandomGatewayCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIPoolGetFromRandomGatewayCall) DoAndReturn(f func(context.Context, string) (Data, error)) *MockIPoolGetFromRandomGatewayCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
